name: 04 - Using Actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: 04-using-actions/react-app 
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Setupr Node
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'
            - name: Install Dependencies
              run: npm ci
            - name: Run Tests
              run: npm run tests


        # 0. Checkout the code from the repository
        # 1. Install deps of our react application
        # 2. Execute automated tests
